<?php
// *** This file is generated by WebsiteBaker Ver.2.8.3
// *** Creation date: 2015-11-03T17:32:05+00:00
// *** Do not modify this file manually
// *** WB will rebuild this file from time to time!!
// *************************************************
	header('HTTP/1.1 301 Moved Permanently');
	header('Location: http://127.0.0.1:4001/wbdemo/index.php');
// *************************************************
