<?php
// *** This file is generated by WebsiteBaker Ver.2.8.3
// *** Creation date: 2016-03-22T18:45:57+00:00
// *** Do not modify this file manually
// *** WB will rebuild this file from time to time!!
// *************************************************
	$page_id    = 2;
	$section_id = 2;
	$post_id    = 6;
	$post_section = 2;
	require('../../index.php');
// *************************************************
