<?php
// *** This file is generated by WebsiteBaker Ver.2.8.3
// *** Creation date: 2016-02-14T18:07:31+00:00
// *** Do not modify this file manually
// *** WB will rebuild this file from time to time!!
/* -------------------------------------------------------- */
// Must include code to stop this file being accessed directly 
if(defined('WB_PATH') == false) { die('Illegale file access /'.basename(__DIR__).'/'.basename(__FILE__).''); }
/* -------------------------------------------------------- */

